### ISSUE TITLE
Highlighting not appearing locally

### ISSUE THREAD

**Issue by darsnack** [MichaelHatherly/Publish.jl#7]
None of my code blocks have syntax highlighting when served locally, but they look fine when deployed. Is this intended?

**Comment by MichaelHatherly** [comment]
It's working locally for me, could a have a few more details on this one?

**Comment by darsnack** [comment]
Yeah let me clarify. I have custom CSS, JS, and HTML (below). I get an error on the HTML on the following line that `Can't find variable hljs`.

```html
<script>hljs.initHighlightingOnLoad();</script>
```

Here is what my code blocks look like locally:
<img width="816" alt="Screen Shot 2020-12-25 at 9 05 18 AM" src="https://user-images.githubusercontent.com/4811350/103137650-50d05e80-4690-11eb-9e72-a84600aa3df9.png">

Here is what they look like deployed:
<img width="817" alt="Screen Shot 2020-12-25 at 9 06 19 AM" src="https://user-images.githubusercontent.com/4811350/103137662-75c4d180-4690-11eb-8cb5-3cfedd18fb4a.png">

Comparing the two in the web inspector shows that the deployed page loads `highlight.min.js` whereas the local page does not.

<details>
<summary>Custom additional CSS</summary>

```css

/* font imports */

@import url('https://fonts.googleapis.com/css2?family=Vollkorn:ital@0;1&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@500&display=swap');

:root {
    --content-width: 90ch;
    --margin-width: 240px;
    --nav-width: 160px;
}

div.content {
    display: flex;
    flex-direction: row;
    flex: 1 1 auto;
    margin-top: 50px;
}

main {
    margin-top: auto;
}

main#page {
    padding: 10px;
    margin-left: calc(var(--nav-width) + 1em);
}

/* # Article container */

article {
    max-width: var(--content-width);
    margin-left: auto;
    margin-right: auto;
    margin-top: 24px;
}

img {
    max-width: var(--content-width);
}


/* fonts */

p, li, td, th {
    color: #111111;
    font-family: 'Vollkorn', serif;
    font-style: normal;
    font-weight: normal;
    font-size: 18px;
    line-height: 24px;
}

p {
    margin-block-start: 8px;
    margin-block-end: 20px;
}


h2 {
    margin-top: 48px;
    font-size: 30px;
}

h3 {
    margin-top: 32px;
    font-size: 24px;
}


h1, h2, h3, h4, h5 {
    font-family: 'Vollkorn', serif;
    font-size: 22px;
    font-weight: bold;
    color: #333;
}

h3 {

    font-weight: bold;
    font-size: 20px;
    margin-bottom: 8px;
}

h1 {
    font-size: 30px;
}

hr {
    margin-top: 50px;
    margin-bottom: 50px;
    max-width: 200px;
    color: #aaa;
}

code {
    font-family: 'Fira Code', 'JuliaMono', monospace;
    font-style: normal;
    font-size: 15px;
    padding: 2px;
    border-radius: 2px;
}

pre > code {
    overflow-x: auto;
    display: block;
    line-height: 125%;
    border-radius: 0px;
    padding: 8px;
    background-color: #f9f9f9;
}

h3 code {
    font-size: 20px;
}

h2 code {
    font-size: 20px;
}

a > code {
    color: black;
    text-decoration: underline;
}

h3 a > code {
    text-decoration: none
}

code.cell-output {
    color: #444;
    background-color: #ffffff;
}

pre {
    margin: 8px 0px;
}

/* Tables */

table {
    margin: 16px 16px;
    overflow-x: auto;
    display: block;
}
th + th , td + td{
    padding-left: 12px;
}

th {
    font-style: italic;
    padding-bottom: 8px;
    margin-bottom: 8px;
}

li > * {
    margin-top: 8px;
    margin-bottom: 8px;
}

.marginnote {
    float: right;
    font-size: 14px;
    width: var(--margin-width);
    clear: right;
    margin-top: 0.25rem;
    margin-bottom: 0;
    margin-left: calc(var(--content-width) + 20px);
    line-height: 1.3;
    vertical-align: baseline;
    position: absolute;
}

/*
Admonitions
*/

.admonition {
    margin: 16px 16px;
    border-top: 1px solid #aaa;
    border-bottom: 1px solid #aaa;
}

.admonition-title {
    font-weight: bold;
}

.admonition > * {
    margin-left: 8px;
    margin-right: 8px;
}

.admonition.info {
    background-color: rgba(135, 206, 235, 0.1);
    
}
/*
Footnotes
*/

a.footnote {
    vertical-align: super;
    font-size: 0.5em;
    margin-left: 2px;
}

div.footnote {
    margin: 16px 16px;
    border-top: 1px solid #aaa;
    border-bottom: 1px solid #aaa;
}

div.footnote > p {
    margin: 8px;
    display: inline;
}

div.footnote > p.footnote-title {
    display: inline;
}

/* # Menu container */

/* .menu {
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
    display: flex;
    flex-direction: row;
    align-items: left;
    margin-top: 8px;
    height: 40px;
} */

#menu-toggler {
    cursor: pointer;
}
#search-input {
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 19px;
    margin: 0px 8px;
    flex-grow: 1;
    padding: 4px 8px;
}

#version-selector {
    border: 1px solid #ddd;
    padding: 4px;
    border-radius: 4px;
}

#page-navigation {
    max-width: var(--content-width);
    margin-left: auto;
    margin-top: 48px;
    margin-right: auto;
}
#page-navigation > a {
    color: #aaa;
    padding: 0px 32px;
    text-decoration: none;
    background: unset;
    text-shadow: unset;
}
#page-navigation > #next-page {
    float: right;
}

/* # Table of contents container */

nav {
    width: var(--nav-width);
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
}


.katex {
    font-size: 15px;
}

footer {
    margin-left: auto;
    margin-right: auto;
    margin-top: 32px;
    margin-bottom: 16px;
    color: #aaa;
    width: 300px;
}
@media (max-width: 1260px) {
    .marginnote {
        float: none;
        margin: 18px 8px;
        width: 100%;
        position: relative;
    }
}

@media (max-width: 760px) {
    article {
        margin-left: 12px;
        margin-right: 12px;
    }
    .marginnote {
        float: none;
        margin: 16px 8px;
        width: 100%;
    }
    img {
        max-width: 100%;
    }
    .menu {
        margin-left: 8px;
        margin-right: 8px;
        padding-right: 0px;
    }
    nav {
        width: 100%;
        display: none;
        justify-content: center;
        position: relative;
        align-self: center;
    }
    main#page {
        margin-left: auto;
    }
    div.content {
        display: block;
    }
}

/* Links

from https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css

*/

/* Links: replica

/* Links: replicate underline that clears descenders */
a:link,
a:visited {
    color: inherit;
}

.no-tufte-underline:link {
    background: unset;
    text-shadow: unset;
}

a:link, .tufte-underline, .hover-tufte-underline:hover {
    text-decoration: none;
    background: -webkit-linear-gradient(#fffff8, #fffff8), -webkit-linear-gradient(#fffff8, #fffff8), -webkit-linear-gradient(currentColor, currentColor);
    background: linear-gradient(#fffff8, #fffff8), linear-gradient(#fffff8, #fffff8), linear-gradient(currentColor, currentColor);
    -webkit-background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    -moz-background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    background-size: 0.05em 1px, 0.05em 1px, 1px 1px;
    background-repeat: no-repeat, no-repeat, repeat-x;
    text-shadow: 0.03em 0 #fffff8, -0.03em 0 #fffff8, 0 0.03em #fffff8, 0 -0.03em #fffff8, 0.06em 0 #fffff8, -0.06em 0 #fffff8, 0.09em 0 #fffff8, -0.09em 0 #fffff8, 0.12em 0 #fffff8, -0.12em 0 #fffff8, 0.15em 0 #fffff8, -0.15em 0 #fffff8;
    background-position: 0% 93%, 100% 93%, 0% 93%;
}

@media screen and (-webkit-min-device-pixel-ratio: 0) {
    a:link, .tufte-underline, .hover-tufte-underline:hover {
        background-position-y: 87%, 87%, 87%;
    }
}

a:link::selection,
a:link::-moz-selection {
    text-shadow: 0.03em 0 #b4d5fe, -0.03em 0 #b4d5fe, 0 0.03em #b4d5fe, 0 -0.03em #b4d5fe, 0.06em 0 #b4d5fe, -0.06em 0 #b4d5fe, 0.09em 0 #b4d5fe, -0.09em 0 #b4d5fe, 0.12em 0 #b4d5fe, -0.12em 0 #b4d5fe, 0.15em 0 #b4d5fe, -0.15em 0 #b4d5fe;
    background: #b4d5fe;
}
```
</details>

<details>
<summary>Custom default JS</summary>

```js
function toggleIndexPage() {
    var page = document.getElementById("page");
    var toc = document.getElementById("toc");
    // Get the current page state. Default to 'page'.
    var state = localStorage.getItem("pageState");
    var margin = localStorage.getItem("contentMargin");
    var mobile = localStorage.getItem("mobile");
    // Toggle index based on 'state'.
    if (state === "page") {
        // Save the current scroll position on the page.
        localStorage.setItem("scrollTop", document.documentElement.scrollTop);
        // Hide the page and display the table-of-contents.
        // page.style.display = "none";
        toc.style.display = "block";
        if (mobile === "true") {
            page.style.display = "none";
        } else {
            page.style.marginLeft = margin;
        }
        // Scroll to the top of the table of contents.
        document.documentElement.scrollTop = 0;
        localStorage.setItem("pageState", "index");
    } else if (state === "index") {
        // Hide the table-of-contents and display the page.
        toc.style.display = "none";
        page.style.display = "block";
        page.style.marginLeft = "auto";
        // page.style.display = "block";
        // Restore the saved position on the page.
        document.documentElement.scrollTop = localStorage.getItem("scrollTop");
        localStorage.setItem("pageState", "page");
    }
}

function getQueryVariable(variable) {
    var query = window.location.search.substring(1);
    var vars = query.split("&");
    for (var i=0; i<vars.length; i++) {
        var pair = vars[i].split("=");
        if (pair[0] == variable) {
            return pair[1];
        }
    }
    return null;
}

function triggerEvent(type, obj, data){
    var ev;
    if (document.createEvent) {
        ev = document.createEvent("HTMLEvents");
        ev.initEvent(type, true, true);
    } else {
        ev = document.createEventObject();
        ev.eventType = type;
    }
    ev.eventName = type;
    if (data) {
        for (var key in data) {
            if (data.hasOwnProperty(key)) {
                ev[key] = data[key];
            }
        }
    }
    if (document.createEvent) {
        obj.dispatchEvent(ev);
    } else {
        obj.fireEvent("on" + ev.eventType, ev);
    }
}

window.addEventListener("searchIndexLoaded", function (_) {
    var search = getQueryVariable("search");
    var div = document.getElementById("search-results");
    if (search !== null && div.innerHTML == "") {
        var search = decodeURIComponent(search);
        var results = window.searchIndex.search(search);
        var details = document.createElement("p");
        div.appendChild(details);
        details.innerHTML = "Results: " + results.length;
        results.forEach(function (item) {
            var p = document.createElement("p");
            div.appendChild(p);
            var a = document.createElement("a");
            a.href = item["ref"];
            a.innerText = item["ref"];
            p.appendChild(a);
        });
    }
});

var mql = window.matchMedia('screen and (max-width:760px)');
mql.addEventListener("change",
    function(mq) {
        if (mq.matches) {
            localStorage.setItem("mobile", true);
            localStorage.setItem("pageState", "page");
        } else {
            localStorage.setItem("mobile", false);
            localStorage.setItem("pageState", "index");
        }
    }
);

document.addEventListener("DOMContentLoaded", function () {
    if (window.matchMedia('(max-width:760px)').matches) {
        localStorage.setItem("mobile", true);
    } else {
        localStorage.setItem("mobile", false);
    }
    // Hide the navigation section.
    if (localStorage.getItem("mobile") === "true") {
        localStorage.setItem("pageState", "page");
    } else {
        localStorage.setItem("pageState", "index");
    }
    localStorage.setItem("contentMargin", document.getElementById("page").style.marginLeft);
    // Tabulator init.
    var table = document.getElementById("docstring-index");
    if (table !== null) {
        var table = new Tabulator("#docstring-index", {
            layout: "fitColumns",
            persistentSort:true,
            persistenceMode:"local",
            columns: [
                {title: "Name", formatter: "html", headerFilter:true},
                {title: "Module", formatter: "html", headerFilter:true},
                {title: "Visibility", formatter: "html", headerFilter:true},
                {title: "Category", formatter: "html", headerFilter:true},
            ],
            initialSort: [
                {column: "name", dir: "asc"},
            ],
        });
    }
    // Version selector.
    if (PUBLISH_VERSIONS !== null) {
        var version_selector = document.querySelector("#version-selector");
        PUBLISH_VERSIONS.forEach(function (each) {
            var name = each[0];
            var path = each[1];
            version = document.createElement("option");
            version.value = path;
            version.text = name;
            version_selector.appendChild(version);
            // Set the current version.
            if (name == PUBLISH_VERSION) {
                version_selector.value = path;
            }
        });
        version_selector.addEventListener("change", function(_) {
            var url = version_selector.options[version_selector.selectedIndex].value;
            window.location.href = url;
        });
    }
    let searchBuilder = new lunr.Builder;
    searchBuilder.ref("id");
    searchBuilder.field("body");
    // Background loading of search index.
    var feedLoaded = function (e) {
        var feed = JSON.parse(e.target.response);
        feed.forEach(function (entry) {
            searchBuilder.add(entry);
        });
        window.searchIndex = searchBuilder.build();
        triggerEvent("searchIndexLoaded", window, {});
    }
    // Fire off the request for the JSON search data.
    if (getQueryVariable("search") !== null) {
        var xhr = new XMLHttpRequest;
        xhr.open('get', PUBLISH_ROOT + '/search.json');
        xhr.addEventListener("load", feedLoaded);
        xhr.send();
    }
    // Hook up the searchbar.
    var search_bar = document.getElementById("search-input");
    search_bar.addEventListener("change", function (event) {
        window.location.href = PUBLISH_ROOT + "/search.html?search=" + encodeURIComponent(event.target.value);
    });
});
```
</details>

<details>
<summary>Custom HTML template</summary>

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="${lang}">
<head>
    <meta charset="utf-8" />
    <meta name="generator" content="Publish.jl" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="${#keywords}${.}${^.[end]} ${/.[end]}${/keywords}" />
    ${#authors}
    <meta name="author" content="${.}" />
    ${/authors}
    <title>${#subtitle}${subtitle} - ${/subtitle}${title}</title>
    ${#html.default_css}
    <link rel="stylesheet" href="${.}" />
    ${/html.default_css}
    ${#html.default_js}
    <script src="${.}"></script>
    ${/html.default_js}
    ${#html.css}
    <link rel="stylesheet" href="${.}" />
    ${/html.css}
    ${#html.js}
    <script src="${.}"></script>
    ${/html.js}
    ${{html.header}}
</head>
<body>
    <div class="menu">
        <svg id="menu-toggler" title="Contents" onclick="toggleIndexPage()" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 6C2 5.44772 2.44772 5 3 5H21C21.5523 5 22 5.44772 22 6C22 6.55228 21.5523 7 21 7H3C2.44772 7 2 6.55228 2 6Z" fill="currentColor" /><path d="M2 12.0322C2 11.4799 2.44772 11.0322 3 11.0322H21C21.5523 11.0322 22 11.4799 22 12.0322C22 12.5845 21.5523 13.0322 21 13.0322H3C2.44772 13.0322 2 12.5845 2 12.0322Z" fill="currentColor" /><path d="M3 17.0645C2.44772 17.0645 2 17.5122 2 18.0645C2 18.6167 2.44772 19.0645 3 19.0645H21C21.5523 19.0645 22 18.6167 22 18.0645C22 17.5122 21.5523 17.0645 21 17.0645H3Z" fill="currentColor" /></svg>
        <input id="search-input" placeholder="Search">
        <select id="version-selector"></select>
    </div>
    <div class="content">
        <nav id="toc">${{html.toc}}</nav>
        <main id="page"><article>${{body}}</article>
            <div id="page-navigation">
                <a id="previous-page" title="Previous" href="${html.prev}"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.2426 6.34317L14.8284 4.92896L7.75739 12L14.8285 19.0711L16.2427 17.6569L10.5858 12L16.2426 6.34317Z" fill="currentColor" /></svg></a>
                <a id="next-page" title="Next" href="${html.next}"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10.5858 6.34317L12 4.92896L19.0711 12L12 19.0711L10.5858 17.6569L16.2427 12L10.5858 6.34317Z" fill="currentColor" /></svg></a>
            </div>
        </main>
    </div>
    <footer>
        Built with <a target="_blank" href="https://github.com/MichaelHatherly/Publish.jl">Publish.jl</a> and the <a target="_blank" href="https://julialang.org">Julia Language.</a>
    </footer>
    <script>hljs.initHighlightingOnLoad();</script>
</body>
</html>
```
</details>

**Comment by MichaelHatherly** [comment]
What's the contents of `Project.toml`?

**Comment by MichaelHatherly** [comment]
Perhaps there's something in the browser blocking the local js?

**Comment by darsnack** [comment]
I tried using a different browser, but the issue is the same.

Here is the `Project.toml`:
```toml
name = "ParameterSchedulers"
uuid = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
authors = ["Kyle Daruwalla"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
Flux = "0.11"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
title = "ParameterSchedulers.jl"

    [publish.html]
    css = "docs/custom.css"
    default_js = "docs/custom.js"

        [publish.html.template]
        file = "docs/custom.mustache"

[targets]
test = ["Test"]
```
